name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup
        uses: actions/setup-node@master
        with:
          node-version: "14"

      - name: dependencies
        run: npm ci

      - name: build
        run: npx ng build --configuration production

      - name: deploy
        uses: jakejarvis/s3-sync-action@master
        with:
          args:
            --acl public-read --delete # --delete means that files that do not
            # exist in the source folder but exist in
            # the destination folder will be deleted
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.S3_BUCKET_REGION }}
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          SOURCE_DIR: dist/nuntium
