name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup
        uses: actions/setup-node@master
        with:
          node-version: "14"

      - name: dependencies
        run: npm ci

      - name: lint
        run: npm run lint
